### ISSUE TITLE
Multisite installation fails

### ISSUE THREAD

**Issue by davidt-de** [Codestag/geeklove-assistant#1]
upon installing this requested plugin an uncaught error happens. It seems this plugin cannot be activited in a multisite environment.

![Bildschirmfoto 2020-06-24 um 07 23 18](https://user-images.githubusercontent.com/44868497/85504146-a8134a80-b5eb-11ea-9845-6e58869ed8b0.png)

Fatal error: Uncaught Error: Call to undefined function stag_check_third_party_seo() in /www/htdocs/w008f29e/blog.davidt.de/wp-content/plugins/geeklove-assistant/includes/metaboxes/seo.php:83 Stack trace: #0 /www/htdocs/w008f29e/blog.davidt.de/wp-includes/class-wp-hook.php(287): stag_metabox_seo_description('') #1 /[...]/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /[...]/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /[...]wp-includes/general-template.php(2884): do_action('wp_head') #4 //[...]/wp-content/themes/geeklove/header.php(13): wp_head() #5 /[...]/wp-includes/template.php(723): require_once('/www/htdocs/w00...') #6 //[...]/wp-includes/template.php(672): load_template('/www/htdocs/w00...', true) #7 //[...]/wp-includes/general-template.php(41): locate_template(Array, true) #8 / in /[...]/wp-content/plugins/geeklove-assistant/includes/metaboxes/seo.php on line 83

**Comment by lushkant** [comment]
Hi there @georgelucas0815, 

Thanks for bringing this to our attention, we've pushed an update fixing the same today ones approved by TF it'll be available to you by this weekend.

Stay safe & stay happy!
